### ISSUE TITLE
Latest docker image is not available

### ISSUE THREAD

**Issue by Programmeris** [datalens-tech/datalens-ui#1529]
Latest datalens-ui version is 0.2092.0, but docker image for this version is not available.

`
docker pull ghcr.io/datalens-tech/datalens-ui:0.2092.0
Error response from daemon: manifest unknown
`

Why is the docker image not built automatically for each version?

**Comment by Marginy605** [comment]
@Programmeris , hi! The latest available version for datalens-ui is 0.2140.0, and the previous version was 0.2000.0 (https://github.com/datalens-tech/datalens/releases/tag/v1.12.0). See release history in **main** repository https://github.com/datalens-tech/datalens/releases. 
We do not build images for each commit in datalens-ui in proper, that's our decision. That's why there is no image for 0.2092.0 version.
